
language: generic

dist: bionic

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
    - ROS_DISTRO="melodic"
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - UPSTREAM_WORKSPACE=file
    - TARGET_WORKSPACE='. -bwi_manipulation'
    # - BUILD_PKGS_WHITELIST="bwi_common"
    # - DB_BACKEND="PostgreSQL"
  matrix:
    - ROS_DISTRO="melodic"

services:
  - postgresql

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
before_cache:
  - sudo chown -R travis:travis $HOME/.ccache
  - ccache -s
