language: generic

env:
  global:
    - CATKIN_CONFIG='--no-install'  # work around kinova-ros install bug
    - ROS_DISTRO="kinetic"
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - UPSTREAM_WORKSPACE=file
    - BUILD_PKGS_WHITELIST="bwi_common"
  matrix:
    - ROS_DISTRO="indigo"
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
