mode: 'train'
# GP model parameters
model: 'setting_1.pth'
kernel: uniform # ['uniform' or 'seperate'] for lengthscale of the GP model
load_from: '8m_contextual.txt' # if mode=='train', use '8m_contextual.txt'
range: -1 # -1 for 'train' mode 
features: # features tag
  - d1
  - d2
  - d3
  - d4
reward: reward # What GP model will predict
reward_clip: [-.Inf,0]
data_format: # header for data storing
  - type
  - wx
  - wy
  - d1
  - d2
  - d3
  - d4
  - E_reward
  - roberto_reward
  - marvin_reward
  - reward
n_samples: 200
sample_range: # lower left pt, upper right pt
  - [-40,-40]
  - [ 40, 40]
# Define Bandit params
epsilon: 0.1
